server:
  port: 9092

spring:
  amqp:
    deserialization:
      trust:
        all: true
  rabbitmq:
    host: localhost
    port: 5672
    username: java11
    password: 123
  data:
    mongodb:
      host: localhost
      port: 27017
      database: UserProfileDB
      username: defaultUser
      password: bilge!*123


my-application:
  secret-key: "bAjAfl&ato9ruwrichlyUc1Lfaprafr8soNoCr!BramaTR7mojicr1wRI0*oC3is"
  secret-key-2: ${SECRETKEY}

usermicroservice:
  redis:
    host: localhost
    port: 6379
rabbitmq:
  exchange-user: auth-exchange
  register-key: register-key
  queue-register: register-queue
  register-mail-key: register-mail-key
  register-mail-queue: register-mail-queue